url: "http://localhost:4000"

paginate: 10

markdown: pandoc
pandoc:
  extensions: [mathjax]
permalink: pretty

baseurl: "http://math.uchicago.edu/~asilata/"
  
exclude: ['deploy', 'stylesheet.scss', 'themes']
