url: "http://localhost:4000"

kramdown:
  parse_block_html: true

permalink: pretty

baseurl: "http://math.uchicago.edu/~asilata/"
  
exclude: ['deploy', 'stylesheet.scss']

analytics_id: "UA-52510464-1"

defaults:
  -
    scope:
      path: ""
    values:
      analytics: true
