name: Build and publish to GitHub Pages
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: build on emacs
      uses: docker://iquiv/alpine-emacs
      if: github.event.deleted == false
      with:
        args: ./build.sh

    - name: Publish to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: success()
      with:
        branch: gh-pages
        folder: public
