name: Build and publish to GitHub Pages
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install emacs
      run: sudo add-apt-repository ppa:kelleyk/emacs --yes
      run: sudo apt update --yes
      run: sudo apt install emacs-nox --yes

    - name: Build website
      run: ./build.sh

    - name: Publish to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: success()
      with:
        branch: gh-pages
        folder: public
