name: Build and publish to GitHub Pages
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install emacs
      uses: purcell/setup-emacs@master
      with:
        version: 27.2

    - name: Build website
      run: ./build.sh

    - name: Run latex
      uses: xu-cheng/latex-actions@v2
      with:
        working_directory: ./cv
        root_file: cv.tex

    - name: Publish to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: success()
      with:
        branch: gh-pages
        folder: public
